server:
  port: 8080

spring:
  datasource:
    username: root
    password: admin
    url: jdbc:mysql://47.93.129.218:3306/test123?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: localhost
    port: 6379
    database: 0

mybatis:
  mapper-locations: classpath*:/mapper/*Mapper.xml

#showSql
logging:
  level:
    root: debug